spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres
    username: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  servlet:
    context-path: /api