spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  servlet:
    context-path: /api