<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://www.cleverbuilder.com/BookService/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <wsdl:types>
        <xs:schema>
            <xs:complexType name="SomeType">
                <xs:sequence>
                    <xs:element name="someDate" type="xs:dateTime"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>

</wsdl:definitions>